In [1]:
import pandas as pd

In [4]:
a =pd.Series([1,5,5,9,7,9,3])
a

0    1
1    5
2    5
3    9
4    7
5    9
6    3
dtype: int64

In [6]:
type(a)

pandas.core.series.Series

In [7]:
a.axes

[RangeIndex(start=0, stop=7, step=1)]

In [8]:
a.dtype

dtype('int64')

In [9]:
a.size

7

In [10]:
a.ndim

1

In [12]:
a.values

array([1, 5, 5, 9, 7, 9, 3], dtype=int64)

In [13]:
a.head

<bound method NDFrame.head of 0    1
1    5
2    5
3    9
4    7
5    9
6    3
dtype: int64>

In [14]:
a.tail(3)

4    7
5    9
6    3
dtype: int64

In [15]:
pd.Series([99,554,878,226,987])

0     99
1    554
2    878
3    226
4    987
dtype: int64

In [16]:
pd.Series([99,554,878,226,987],index=["a","b","c","d","we"])

a      99
b     554
c     878
d     226
we    987
dtype: int64

In [17]:
seri=pd.Series([99,554,878,226,987],index=["a","b","c","d","we"])

In [18]:
seri["a"]

99

In [ ]:
dictionary={"reg":10,"log":11,"cart":12}

In [21]:
seri = pd.Series(dictionary)

In [22]:
seri

reg     10
log     11
cart    12
dtype: int64

In [27]:
pd.concat([seri,seri],axis=1)

0   1
reg   10  10
log   11  11
cart  12  12

In [28]:
## Eleman işlemleri

In [29]:
import numpy as np
a = np.array([1,2,33,444,75])

In [30]:
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4     75
dtype: int32

In [31]:
seri[0]

1

In [32]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [33]:
seri2=pd.Series([99,554,878,226,987],
               index=["ab","bc","cd","de","wez"])

In [34]:
seri2

ab      99
bc     554
cd     878
de     226
wez    987
dtype: int64

In [35]:
seri2.index

Index(['ab', 'bc', 'cd', 'de', 'wez'], dtype='object')

In [36]:
seri2.keys

<bound method Series.keys of ab      99
bc     554
cd     878
de     226
wez    987
dtype: int64>

In [38]:
list(seri2.items())

[('ab', 99), ('bc', 554), ('cd', 878), ('de', 226), ('wez', 987)]

In [39]:
seri2.values

array([ 99, 554, 878, 226, 987], dtype=int64)

In [40]:
"a" in seri2

False

In [41]:
"b" in seri2

False

In [42]:
"ab" in seri2

True

In [44]:
seri2["ab"]

99

In [49]:
seri2[['ab','cd','wez']]

ab      99
cd     878
wez    987
dtype: int64

In [48]:
seri2['ab':'cd']

ab     99
bc    554
cd    878
dtype: int64

In [51]:
l = [1,554,89,564,13,78]

pd.DataFrame(l,columns=["deg_ismi"])

deg_ismi
0         1
1       554
2        89
3       564
4        13
5        78

In [65]:
m22 = np.arange(0,100,5).reshape((4,5))
m22

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [69]:
p = pd.DataFrame(m22, columns=["Maaş","Maaş2","Maaş3","Maaş2","Maaş3"])
p

Maaş  Maaş2  Maaş3  Maaş2  Maaş3
0     0      5     10     15     20
1    25     30     35     40     45
2    50     55     60     65     70
3    75     80     85     90     95

In [70]:
p.columns

Index(['Maaş', 'Maaş2', 'Maaş3', 'Maaş2', 'Maaş3'], dtype='object')

In [73]:
a = p.rename({'Maaş':'Maaş1'})
a

Maaş  Maaş2  Maaş3  Maaş2  Maaş3
0     0      5     10     15     20
1    25     30     35     40     45
2    50     55     60     65     70
3    75     80     85     90     95

In [74]:
type(a)

pandas.core.frame.DataFrame

In [75]:
a.axes

[Int64Index([0, 1, 2, 3], dtype='int64'),
 Index(['Maaş', 'Maaş2', 'Maaş3', 'Maaş2', 'Maaş3'], dtype='object')]

In [76]:
a.shape

(4, 5)

In [77]:
a.ndim

2

In [79]:
a.size

20

In [80]:
a.values

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45],
       [50, 55, 60, 65, 70],
       [75, 80, 85, 90, 95]])

In [81]:
a.tail

<bound method NDFrame.tail of    Maaş  Maaş2  Maaş3  Maaş2  Maaş3
0     0      5     10     15     20
1    25     30     35     40     45
2    50     55     60     65     70
3    75     80     85     90     95>

In [82]:
s1 = np.random.randint(10, size=5)
s2 = np.random.randint(10, size=5)
s3 = np.random.randint(10, size=5)

In [83]:
sozluk = {"var1":s1,"var2":s2,"var3":s3}

In [84]:
sozluk

{'var1': array([8, 0, 0, 6, 4]),
 'var2': array([4, 9, 3, 2, 9]),
 'var3': array([5, 6, 0, 3, 1])}

In [86]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     8     4     5
1     0     9     6
2     0     3     0
3     6     2     3
4     4     9     1

In [87]:
df.iloc[0:1]

var1  var2  var3
0     8     4     5

In [88]:
df.iloc[0:2]

var1  var2  var3
0     8     4     5
1     0     9     6

In [90]:
df.index = ["*","*","*","*","*"]

In [91]:
df

var1  var2  var3
*     8     4     5
*     0     9     6
*     0     3     0
*     6     2     3
*     4     9     1

In [94]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     8     4     5
b     0     9     6
c     0     3     0
d     6     2     3
e     4     9     1

In [95]:
df.drop("a",axis=0)

var1  var2  var3
b     0     9     6
c     0     3     0
d     6     2     3
e     4     9     1

In [96]:
df

var1  var2  var3
a     8     4     5
b     0     9     6
c     0     3     0
d     6     2     3
e     4     9     1

In [97]:
df.drop("a",axis=0,inplace=True)

In [98]:
df

var1  var2  var3
b     0     9     6
c     0     3     0
d     6     2     3
e     4     9     1

In [99]:
l = ["b","c"]

In [100]:
df.drop(l,axis=0,inplace=True)

In [101]:
df

var1  var2  var3
d     6     2     3
e     4     9     1

In [102]:
"var1" in df

True

In [103]:
l = ["var1","var4","var2"]

In [108]:
for i in l:
    print(i in df)

True
False
True


In [109]:
df

var1  var2  var3
d     6     2     3
e     4     9     1

In [110]:
df["var1"]

d    6
e    4
Name: var1, dtype: int32

In [111]:
df["var4"] = df["var1"] * df["var2"]

In [112]:
df

var1  var2  var3  var4
d     6     2     3    12
e     4     9     1    36

In [115]:
df.rename(columns={"var1":"var0"})

var0  var2  var3  var4
d     6     2     3    12
e     4     9     1    36

In [116]:
l = ["var1","var2"]

In [117]:
df.drop(l,axis=1)

var3  var4
d     3    12
e     1    36

In [118]:
m = np.random.randint(1,30,size=(10,3))
df = pd.DataFrame(m,columns=["var1","var2","var3"])
df

var1  var2  var3
0    17    26    23
1    21    19     5
2     5    22    22
3    29    17     2
4    16    23    24
5    28    12     7
6     5     6    11
7     1     4    25
8    29     6    14
9    17     1    21

In [119]:
?np.random.randint

In [120]:
'''
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the ``integers`` method of a ``default_rng()``
    instance instead; please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-like, must contain integer values
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
dtype : dtype, optional
    Desired dtype of the result. Byteorder must be native.
    The default value is int.

    .. versionadded:: 1.11.0

Returns
-------
out : int or ndarray of ints
    `size`-shaped array of random integers from the appropriate
    distribution, or a single such random int if `size` not provided.

See Also
--------
random_integers : similar to `randint`, only for the closed
    interval [`low`, `high`], and 1 is the lowest value if `high` is
    omitted.
Generator.integers: which should be used for new code.

Examples
--------
>>> np.random.randint(2, size=10)
array([1, 0, 0, 0, 1, 1, 0, 0, 1, 0]) # random
>>> np.random.randint(1, size=10)
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Generate a 2 x 4 array of ints between 0 and 4, inclusive:

>>> np.random.randint(5, size=(2, 4))
array([[4, 0, 2, 1], # random
       [3, 2, 2, 0]])

Generate a 1 x 3 array with 3 different upper bounds

>>> np.random.randint(1, [3, 5, 10])
array([2, 2, 9]) # random

Generate a 1 by 3 array with 3 different lower bounds

>>> np.random.randint([1, 5, 7], 10)
array([9, 8, 7]) # random

Generate a 2 by 4 array using broadcasting with dtype of uint8

>>> np.random.randint([1, 3, 5, 7], [[10], [20]], dtype=np.uint8)
array([[ 8,  6,  9,  7], # random
       [ 1, 16,  9, 12]], dtype=uint8)
Type:      builtin_function_or_method

'''

'\nDocstring:\nrandint(low, high=None, size=None, dtype=int)\n\nReturn random integers from `low` (inclusive) to `high` (exclusive).\n\nReturn random integers from the "discrete uniform" distribution of\nthe specified dtype in the "half-open" interval [`low`, `high`). If\n`high` is None (the default), then results are from [0, `low`).\n\n.. note::\n    New code should use the ``integers`` method of a ``default_rng()``\n    instance instead; please see the :ref:`random-quick-start`.\n\nParameters\n----------\nlow : int or array-like of ints\n    Lowest (signed) integers to be drawn from the distribution (unless\n    ``high=None``, in which case this parameter is one above the\n    *highest* such integer).\nhigh : int or array-like of ints, optional\n    If provided, one above the largest (signed) integer to be drawn\n    from the distribution (see above for behavior if ``high=None``).\n    If array-like, must contain integer values\nsize : int or tuple of ints, optional\n    Output shap

In [121]:
df.loc[0:3]

var1  var2  var3
0    17    26    23
1    21    19     5
2     5    22    22
3    29    17     2

In [122]:
df.iloc[0:3]

var1  var2  var3
0    17    26    23
1    21    19     5
2     5    22    22

In [123]:
df.iloc[0,0]

17

In [124]:
df.iloc[:3,:2]

var1  var2
0    17    26
1    21    19
2     5    22

In [125]:
df.loc[0:3,"var3"]

0    23
1     5
2    22
3     2
Name: var3, dtype: int32

In [127]:
df.loc[:3,"var3"]

0    23
1     5
2    22
3     2
Name: var3, dtype: int32

In [131]:
df.iloc[0:3,1:2]

var2
0    26
1    19
2    22

In [132]:
df.iloc[0:3]["var3"]

0    23
1     5
2    22
Name: var3, dtype: int32

In [133]:
df["var1"]

0    17
1    21
2     5
3    29
4    16
5    28
6     5
7     1
8    29
9    17
Name: var1, dtype: int32

In [134]:
df[0:2][["var1","var2"]]

var1  var2
0    17    26
1    21    19

In [135]:
## kosullu İşlemler

In [136]:
df.var1

0    17
1    21
2     5
3    29
4    16
5    28
6     5
7     1
8    29
9    17
Name: var1, dtype: int32

In [138]:
df[df.var1>15]

0    26
1    19
3    17
4    23
5    12
8     6
9     1
Name: var2, dtype: int32

In [139]:
df[df.var1>15]["var1"]

0    17
1    21
3    29
4    16
5    28
8    29
9    17
Name: var1, dtype: int32

In [141]:
df[(df.var1>15) & (df.var3<5) ]

var1  var2  var3
3    29    17     2

In [142]:
df.loc[df.var1>15,["var1","var2"]]

var1  var2
0    17    26
1    21    19
3    29    17
4    16    23
5    28    12
8    29     6
9    17     1

In [144]:
m = np.random.randint(1,30,size=(5,3))
df1 = pd.DataFrame(m,columns=["var1","var2","var3"])
df1

var1  var2  var3
0    16    10    16
1    15    14    28
2    23    13     8
3    27    10     8
4    27    24     2

In [145]:
df2 = df + 99

In [149]:
df2

var1  var2  var3
0   116   119   120
1   124   127   108
2   120   115   109
3   128   107   118
4   115   123   128

In [150]:
pd.concat([df1,df2])

var1  var2  var3
0    16    10    16
1    15    14    28
2    23    13     8
3    27    10     8
4    27    24     2
0   116   119   120
1   124   127   108
2   120   115   109
3   128   107   118
4   115   123   128

In [148]:
?pd.concat

Signature:
pd.concat(
    objs: 'Iterable[NDFrame] | Mapping[Hashable, NDFrame]',
    axis: 'Axis' = 0,
    join: 'str' = 'outer',
    ignore_index: 'bool' = False,
    keys=None,
    levels=None,
    names=None,
    verify_integrity: 'bool' = False,
    sort: 'bool' = False,
    copy: 'bool' = True,
) -> 'DataFrame | Series'
Docstring:
Concatenate pandas objects along a particular axis with optional set logic
along the other axes.

Can also add a layer of hierarchical indexing on the concatenation axis,
which may be useful if the labels are the same (or overlapping) on
the passed axis number.

Parameters
----------
objs : a sequence or mapping of Series or DataFrame objects
    If a mapping is passed, the sorted keys will be used as the `keys`
    argument, unless it is passed, in which case the values will be
    selected (see below). Any None objects will be dropped silently unless
    they are all None in which case a ValueError will be raised.
axis : {0/'index', 1/'columns'}, default 0
    The axis to concatenate along.
join : {'inner', 'outer'}, default 'outer'
    How to handle indexes on other axis (or axes).
ignore_index : bool, default False
    If True, do not use the index values along the concatenation axis. The
    resulting axis will be labeled 0, ..., n - 1. This is useful if you are
    concatenating objects where the concatenation axis does not have
    meaningful indexing information. Note the index values on the other
    axes are still respected in the join.
keys : sequence, default None
    If multiple levels passed, should contain tuples. Construct
    hierarchical index using the passed keys as the outermost level.
levels : list of sequences, default None
    Specific levels (unique values) to use for constructing a
    MultiIndex. Otherwise they will be inferred from the keys.
names : list, default None
    Names for the levels in the resulting hierarchical index.
verify_integrity : bool, default False
    Check whether the new concatenated axis contains duplicates. This can
    be very expensive relative to the actual data concatenation.
sort : bool, default False
    Sort non-concatenation axis if it is not already aligned when `join`
    is 'outer'.
    This has no effect when ``join='inner'``, which already preserves
    the order of the non-concatenation axis.

    .. versionchanged:: 1.0.0

       Changed to not sort by default.

copy : bool, default True
    If False, do not copy data unnecessarily.

Returns
-------
object, type of objs
    When concatenating all ``Series`` along the index (axis=0), a
    ``Series`` is returned. When ``objs`` contains at least one
    ``DataFrame``, a ``DataFrame`` is returned. When concatenating along
    the columns (axis=1), a ``DataFrame`` is returned.

See Also
--------
Series.append : Concatenate Series.
DataFrame.append : Concatenate DataFrames.
DataFrame.join : Join DataFrames using indexes.
DataFrame.merge : Merge DataFrames by indexes or columns.

Notes
-----
The keys, levels, and names arguments are all optional.

A walkthrough of how this method fits in with other tools for combining
pandas objects can be found `here
<https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html>`__.

Examples
--------
Combine two ``Series``.

>>> s1 = pd.Series(['a', 'b'])
>>> s2 = pd.Series(['c', 'd'])
>>> pd.concat([s1, s2])
0    a
1    b
0    c
1    d
dtype: object

Clear the existing index and reset it in the result
by setting the ``ignore_index`` option to ``True``.

>>> pd.concat([s1, s2], ignore_index=True)
0    a
1    b
2    c
3    d
dtype: object

Add a hierarchical index at the outermost level of
the data with the ``keys`` option.

>>> pd.concat([s1, s2], keys=['s1', 's2'])
s1  0    a
    1    b
s2  0    c
    1    d
dtype: object

Label the index keys you create with the ``names`` option.

>>> pd.concat([s1, s2], keys=['s1', 's2'],
...           names=['Series name', 'Row ID'])
Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: object

Combine two ``DataFrame`` objects with identical columns.

>>> df1 = pd.DataFrame([['a', 1], ['b', 2]],
...                    columns=['letter', 'number'])
>>> df1
  letter  number
0      a       1
1      b       2
>>> df2 = pd.DataFrame([['c', 3], ['d', 4]],
...                    columns=['letter', 'number'])
>>> df2
  letter  number
0      c       3
1      d       4
>>> pd.concat([df1, df2])
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects with overlapping columns
and return everything. Columns outside the intersection will
be filled with ``NaN`` values.

>>> df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
...                    columns=['letter', 'number', 'animal'])
>>> df3
  letter  number animal
0      c       3    cat
1      d       4    dog
>>> pd.concat([df1, df3], sort=False)
  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

Combine ``DataFrame`` objects with overlapping columns
and return only those that are shared by passing ``inner`` to
the ``join`` keyword argument.

>>> pd.concat([df1, df3], join="inner")
  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

Combine ``DataFrame`` objects horizontally along the x axis by
passing in ``axis=1``.

>>> df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
...                    columns=['animal', 'name'])
>>> pd.concat([df1, df4], axis=1)
  letter  number  animal    name
0      a       1    bird   polly
1      b       2  monkey  george

Prevent the result from including duplicate index values with the
``verify_integrity`` option.

>>> df5 = pd.DataFrame([1], index=['a'])
>>> df5
   0
a  1
>>> df6 = pd.DataFrame([2], index=['a'])
>>> df6
   0
a  2
>>> pd.concat([df5, df6], verify_integrity=True)
Traceback (most recent call last):
    ...
ValueError: Indexes have overlapping values: ['a']
File:      c:\programdata\anaconda3\lib\site-packages\pandas\core\reshape\concat.py
Type:      function

In [151]:
pd.concat([df1,df2], ignore_index = True)

var1  var2  var3
0    16    10    16
1    15    14    28
2    23    13     8
3    27    10     8
4    27    24     2
5   116   119   120
6   124   127   108
7   120   115   109
8   128   107   118
9   115   123   128

In [152]:
pd.concat([df1,df2], ignore_index = False)

var1  var2  var3
0    16    10    16
1    15    14    28
2    23    13     8
3    27    10     8
4    27    24     2
0   116   119   120
1   124   127   108
2   120   115   109
3   128   107   118
4   115   123   128

In [153]:
df2.columns = ["var1","var2","deg3"]

In [154]:
df2

var1  var2  deg3
0   116   119   120
1   124   127   108
2   120   115   109
3   128   107   118
4   115   123   128

In [155]:
pd.concat([df1,df2])

var1  var2  var3   deg3
0    16    10  16.0    NaN
1    15    14  28.0    NaN
2    23    13   8.0    NaN
3    27    10   8.0    NaN
4    27    24   2.0    NaN
0   116   119   NaN  120.0
1   124   127   NaN  108.0
2   120   115   NaN  109.0
3   128   107   NaN  118.0
4   115   123   NaN  128.0

In [156]:
pd.concat([df1,df2], join="inner")

var1  var2
0    16    10
1    15    14
2    23    13
3    27    10
4    27    24
0   116   119
1   124   127
2   120   115
3   128   107
4   115   123

In [159]:
df11 = pd.DataFrame({'calısanlar': ['Ali','Veli','Ayse','Fatma'],
                    'grup': ['Muhasebe','Muhendislik','Muhendislik','İK']})
df11

calısanlar         grup
0        Ali     Muhasebe
1       Veli  Muhendislik
2       Ayse  Muhendislik
3      Fatma           İK

In [160]:
df12 = pd.DataFrame({'calısanlar': ['Ayse','Ali','Veli','Fatma'],
                    'ilk_giris': [2010,2009,2014,2019]})
df12

calısanlar  ilk_giris
0       Ayse       2010
1        Ali       2009
2       Veli       2014
3      Fatma       2019

In [161]:
pd.merge(df11,df12)

calısanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [163]:
pd.merge(df11,df12, on="calısanlar")

calısanlar         grup  ilk_giris
0        Ali     Muhasebe       2009
1       Veli  Muhendislik       2014
2       Ayse  Muhendislik       2010
3      Fatma           İK       2019

In [164]:
df3 = pd.merge(df11,df12)

In [165]:
df4 = pd.DataFrame({'grup':['Muhasebe','Muhendislik','İK'],
                   'mudur': ['Caner','Mustafa','Berkcan']})
df4

grup    mudur
0     Muhasebe    Caner
1  Muhendislik  Mustafa
2           İK  Berkcan

In [167]:
pd.merge(df3,df4)

calısanlar         grup  ilk_giris    mudur
0        Ali     Muhasebe       2009    Caner
1       Veli  Muhendislik       2014  Mustafa
2       Ayse  Muhendislik       2010  Mustafa
3      Fatma           İK       2019  Berkcan

In [168]:
import seaborn as sns

In [169]:
df = sns.load_dataset("planets")

In [171]:
df.head(5)

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [172]:
df.tail(5)

method  number  orbital_period  mass  distance  year
1030  Transit       1        3.941507   NaN     172.0  2006
1031  Transit       1        2.615864   NaN     148.0  2007
1032  Transit       1        3.191524   NaN     174.0  2007
1033  Transit       1        4.125083   NaN     293.0  2008
1034  Transit       1        4.187757   NaN     260.0  2008

In [173]:
df.shape

(1035, 6)

In [177]:
import warnings
warnings.filterwarnings('ignore')

In [178]:
df.mean()

number               1.785507
orbital_period    2002.917596
mass                 2.638161
distance           264.069282
year              2009.070531
dtype: float64

In [179]:
df.mass.mean()

2.6381605847953233

In [180]:
df.count()

method            1035
number            1035
orbital_period     992
mass               513
distance           808
year              1035
dtype: int64

In [181]:
df.isnull().sum()

method              0
number              0
orbital_period     43
mass              522
distance          227
year                0
dtype: int64

In [182]:
df['mass'].min()

0.0036

In [184]:
df['mass'].max()

25.0

In [185]:
df['mass'].std()

3.8186166509616046

In [186]:
df.std()

number                1.240976
orbital_period    26014.728304
mass                  3.818617
distance            733.116493
year                  3.972567
dtype: float64

In [187]:
df.mass.var()

14.58183312700122

In [189]:
df.describe()

number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [190]:
df.describe().T

count         mean           std          min         25%  \
number          1035.0     1.785507      1.240976     1.000000     1.00000   
orbital_period   992.0  2002.917596  26014.728304     0.090706     5.44254   
mass             513.0     2.638161      3.818617     0.003600     0.22900   
distance         808.0   264.069282    733.116493     1.350000    32.56000   
year            1035.0  2009.070531      3.972567  1989.000000  2007.00000   

                      50%       75%       max  
number             1.0000     2.000       7.0  
orbital_period    39.9795   526.005  730000.0  
mass               1.2600     3.040      25.0  
distance          55.2500   178.500    8500.0  
year            2010.0000  2012.000    2014.0

In [191]:
df.dropna().describe().T

count         mean          std        min         25%  \
number          498.0     1.734940     1.175720     1.0000     1.00000   
orbital_period  498.0   835.778671  1469.128259     1.3283    38.27225   
mass            498.0     2.509320     3.636274     0.0036     0.21250   
distance        498.0    52.068213    46.596041     1.3500    24.49750   
year            498.0  2007.377510     4.167284  1989.0000  2005.00000   

                     50%        75%      max  
number             1.000     2.0000      6.0  
orbital_period   357.000   999.6000  17337.5  
mass               1.245     2.8675     25.0  
distance          39.940    59.3325    354.0  
year            2009.000  2011.0000   2014.0

In [196]:
dfG = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'veri': [10,11,52,23,43,55]}, columns=['gruplar','veri'])
dfG

gruplar  veri
0       A    10
1       B    11
2       C    52
3       A    23
4       B    43
5       C    55

In [195]:
np.linspace(10,20,70)

array([10.        , 10.14492754, 10.28985507, 10.43478261, 10.57971014,
       10.72463768, 10.86956522, 11.01449275, 11.15942029, 11.30434783,
       11.44927536, 11.5942029 , 11.73913043, 11.88405797, 12.02898551,
       12.17391304, 12.31884058, 12.46376812, 12.60869565, 12.75362319,
       12.89855072, 13.04347826, 13.1884058 , 13.33333333, 13.47826087,
       13.62318841, 13.76811594, 13.91304348, 14.05797101, 14.20289855,
       14.34782609, 14.49275362, 14.63768116, 14.7826087 , 14.92753623,
       15.07246377, 15.2173913 , 15.36231884, 15.50724638, 15.65217391,
       15.79710145, 15.94202899, 16.08695652, 16.23188406, 16.37681159,
       16.52173913, 16.66666667, 16.8115942 , 16.95652174, 17.10144928,
       17.24637681, 17.39130435, 17.53623188, 17.68115942, 17.82608696,
       17.97101449, 18.11594203, 18.26086957, 18.4057971 , 18.55072464,
       18.69565217, 18.84057971, 18.98550725, 19.13043478, 19.27536232,
       19.42028986, 19.56521739, 19.71014493, 19.85507246, 20.  

In [198]:
df.groupby('gruplar')

In [199]:
df.groupby('gruplar').sum()

veri
gruplar      
A          33
B          54
C         107

In [200]:
df.groupby('gruplar').mean()

veri
gruplar      
A        16.5
B        27.0
C        53.5

In [201]:
df2 = sns.load_dataset("planets")

In [202]:
df2.groupby("method")

In [204]:
df2.groupby("method")["orbital_period"].mean()

method
Astrometry                          631.180000
Eclipse Timing Variations          4751.644444
Imaging                          118247.737500
Microlensing                       3153.571429
Orbital Brightness Modulation         0.709307
Pulsar Timing                      7343.021201
Pulsation Timing Variations        1170.000000
Radial Velocity                     823.354680
Transit                              21.102073
Transit Timing Variations            79.783500
Name: orbital_period, dtype: float64

In [207]:
df2.groupby("method")["orbital_period"].describe().T

method   Astrometry  Eclipse Timing Variations        Imaging  Microlensing  \
count      2.000000                   9.000000      12.000000      7.000000   
mean     631.180000                4751.644444  118247.737500   3153.571429   
std      544.217663                2499.130945  213978.177277   1113.166333   
min      246.360000                1916.250000    4639.150000   1825.000000   
25%      438.770000                2900.000000    8343.900000   2375.000000   
50%      631.180000                4343.500000   27500.000000   3300.000000   
75%      823.590000                5767.000000   94250.000000   3550.000000   
max     1016.000000               10220.000000  730000.000000   5100.000000   

method  Orbital Brightness Modulation  Pulsar Timing  \
count                        3.000000       5.000000   
mean                         0.709307    7343.021201   
std                          0.725493   16313.265573   
min                          0.240104       0.090706   
25%                          0.291496      25.262000   
50%                          0.342887      66.541900   
75%                          0.943908      98.211400   
max                          1.544929   36525.000000   

method  Pulsation Timing Variations  Radial Velocity     Transit  \
count                           1.0        553.00000  397.000000   
mean                         1170.0        823.35468   21.102073   
std                             NaN       1454.92621   46.185893   
min                          1170.0          0.73654    0.355000   
25%                          1170.0         38.02100    3.160630   
50%                          1170.0        360.20000    5.714932   
75%                          1170.0        982.00000   16.145700   
max                          1170.0      17337.50000  331.600590   

method  Transit Timing Variations  
count                    3.000000  
mean                    79.783500  
std                     71.599884  
min                     22.339500  
25%                     39.675250  
50%                     57.011000  
75%                    108.505500  
max                    160.000000

In [210]:
dfb = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'deg1': [10,11,52,23,556,888],
                  'deg2': [43,55,5659,111,59995,87878]},
                   columns=['gruplar','deg1','deg2'])
dfb

gruplar  deg1   deg2
0       A    10     43
1       B    11     55
2       C    52   5659
3       A    23    111
4       B   556  59995
5       C   888  87878

In [211]:
#aggregate

In [214]:
dfb.groupby('gruplar').mean()

deg1     deg2
gruplar                
A         16.5     77.0
B        283.5  30025.0
C        470.0  46768.5

In [217]:
dfb.groupby('gruplar').aggregate(["min",np.median, max])

deg1              deg2                
         min median  max   min   median    max
gruplar                                       
A         10   16.5   23    43     77.0    111
B         11  283.5  556    55  30025.0  59995
C         52  470.0  888  5659  46768.5  87878

In [219]:
dfb.groupby('gruplar').aggregate({"deg1":min,"deg2": np.std})

deg1          deg2
gruplar                    
A          10     48.083261
B          11  42383.980464
C          52  58137.612442

In [225]:
dfg = pd.DataFrame({'gruplar': ['A','B','C','A','B','C'],
                  'deg1': [10,11,52,23,556,888],
                  'deg2': [43,55,5659,111,59995,87878]},
                   columns=['gruplar','deg1','deg2'])
dfg

gruplar  deg1   deg2
0       A    10     43
1       B    11     55
2       C    52   5659
3       A    23    111
4       B   556  59995
5       C   888  87878

In [235]:
dfb.groupby('gruplar').std()

deg1          deg2
gruplar                          
A          9.192388     48.083261
B        385.373196  42383.980464
C        591.141269  58137.612442

In [233]:
def filter_func(x):
    return x["deg1"].std() > 9

In [234]:
dfg.groupby("gruplar").filter(filter_func)

gruplar  deg1   deg2
0       A    10     43
1       B    11     55
2       C    52   5659
3       A    23    111
4       B   556  59995
5       C   888  87878

In [241]:
df_a = dfg.iloc[:,1:3]

In [242]:
df_a.transform(lambda x: x-x.mean())

deg1     deg2
0 -246.666667 -25580.5
1 -245.666667 -25568.5
2 -204.666667 -19964.5
3 -233.666667 -25512.5
4  299.333333  34371.5
5  631.333333  62254.5

In [243]:
df_a.transform(lambda x: x-x.mean() / x.std())

deg1          deg2
0    9.316886     42.334605
1   10.316886     54.334605
2   51.316886   5658.334605
3   22.316886    110.334605
4  555.316886  59994.334605
5  887.316886  87877.334605

In [249]:
dfgp = pd.DataFrame({'deg1': [10,11,52,23,556,888],
                  'deg2': [43,55,5659,111,59995,87878]},
                   columns=['deg1','deg2'])
dfgp

deg1   deg2
0    10     43
1    11     55
2    52   5659
3    23    111
4   556  59995
5   888  87878

In [250]:
dfgp.apply(np.sum)

deg1      1540
deg2    153741
dtype: int64

In [252]:
dfgp.apply(lambda x: x *0.75 - x*0.25 )

deg1     deg2
0    5.0     21.5
1    5.5     27.5
2   26.0   2829.5
3   11.5     55.5
4  278.0  29997.5
5  444.0  43939.0

In [253]:
df.groupby("gruplar").apply(np.sum)

gruplar  veri
gruplar              
A            AA    33
B            BB    54
C            CC   107

In [254]:
titanic = sns.load_dataset('titanic')
titanic.head(5)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [256]:
titanic.groupby("sex")[["survived"]].mean()

survived
sex             
female  0.742038
male    0.188908

In [261]:
titanic.groupby(["sex","class"])[["survived"]].aggregate("mean").unstack()

survived                    
class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [262]:
titanic.pivot_table("survived", index="sex",columns="class")

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [266]:
titanic.pivot_table("survived",["sex","age"],"class")

class         First  Second  Third
sex    age                        
female 0.75     NaN     NaN   1.00
       1.00     NaN     NaN   1.00
       2.00     0.0     1.0   0.25
       3.00     NaN     1.0   0.00
       4.00     NaN     1.0   1.00
...             ...     ...    ...
male   70.00    0.0     0.0    NaN
       70.50    NaN     NaN   0.00
       71.00    0.0     NaN    NaN
       74.00    NaN     NaN   0.00
       80.00    1.0     NaN    NaN

[145 rows x 3 columns]

In [284]:
a = pd.Series([10,50,5])
a

0    10
1    50
2     5
dtype: int64

In [285]:
b = pd.Series([0,5,5])
b

0    0
1    5
2    5
dtype: int64

In [286]:
df1 = pd.concat(a,b)

TypeError: first argument must be an iterable of pandas objects, you passed an object of type "Series"