## Numpy array

In [2]:
import numpy as np

In [4]:
a = np.array([1,2,5,83,554])

In [5]:
type(a)

numpy.ndarray

In [6]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

In [7]:
np.array([3.14,4,2,13],dtype="int")

array([ 3,  4,  2, 13])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones((3,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [11]:
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
np.arange(0,31, 3)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [14]:
np.linspace(0,1,33)

array([0.     , 0.03125, 0.0625 , 0.09375, 0.125  , 0.15625, 0.1875 ,
       0.21875, 0.25   , 0.28125, 0.3125 , 0.34375, 0.375  , 0.40625,
       0.4375 , 0.46875, 0.5    , 0.53125, 0.5625 , 0.59375, 0.625  ,
       0.65625, 0.6875 , 0.71875, 0.75   , 0.78125, 0.8125 , 0.84375,
       0.875  , 0.90625, 0.9375 , 0.96875, 1.     ])

In [15]:
np.random.normal(10,4,(3,4))

array([[11.21418775,  9.12532589, 12.74512081, 14.11816942],
       [ 8.75518042,  7.56261224,  8.64892947,  7.99816961],
       [13.74366739,  7.57647325, 16.19467037,  5.20684059]])

In [17]:
np.random.randint(0,10,(3,3))

array([[9, 3, 7],
       [0, 5, 5],
       [6, 3, 9]])

* **ndim**: boyut sayısı
* **shape**: boyut bilgisi
* **size**: toplam eleman sayısı
* **dtype**: array veri tipi

In [20]:
a = np.random.randint(10, size =10)

In [21]:
a.ndim

1

In [22]:
a.shape

(10,)

In [23]:
a.size

10

In [24]:
a.dtype

dtype('int32')

In [25]:
b = np.random.randint(10, size =(3,5))

In [26]:
b

array([[4, 0, 7, 6, 7],
       [6, 8, 5, 4, 8],
       [7, 6, 3, 4, 4]])

In [27]:
b.ndim

2

In [28]:
b.shape

(3, 5)

In [29]:
b.size

15

In [30]:
b.dtype

dtype('int32')

In [31]:
c = np.arange(1,10)

In [32]:
c.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
x = np.arange(1,10)
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x.ndim 

1

In [45]:
y = x.reshape((1,9))
y

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
y.ndim 

2

In [50]:
import numpy as np

In [51]:
x = np.array([1,2,3])
y = np.array([5,9,8])

In [53]:
np.concatenate([x, y])

array([1, 2, 3, 5, 9, 8])

In [54]:
z = np.array([7,8,9])

In [55]:
np.concatenate([x, y, z])

array([1, 2, 3, 5, 9, 8, 7, 8, 9])

In [58]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.concatenate([a, a])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [61]:
np.concatenate([a, a] ,axis =1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
x = np.array([1,2,3,99,99,3,2,1])

In [65]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [66]:
np.split(x, [1,5])

[array([1]), array([ 2,  3, 99, 99]), array([3, 2, 1])]

In [67]:
a, b, c = np.split(x, [3,5])

In [68]:
a

array([1, 2, 3])

In [69]:
b

array([99, 99])

In [70]:
c

array([3, 2, 1])

In [71]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
np.vsplit(m, [2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [73]:
ax = np.random.randint(0,100,20).reshape(5,4)
ax

array([[34, 10, 74,  2],
       [88, 27, 31, 73],
       [65,  9, 73, 29],
       [34, 57, 74,  8],
       [68, 69, 24, 25]])

In [78]:
bx = np.random.normal(0,1,150).reshape(30,5)
bx

array([[ 9.26566915e-01,  2.63086412e-01, -5.23623850e-01,
         5.36940576e-01, -8.37581816e-01],
       [-1.11193806e+00, -1.51886718e-01, -5.14320283e-01,
         3.52431192e-02, -1.68161385e-01],
       [ 9.12884090e-01, -8.29286749e-01,  2.27332355e-01,
         4.74143673e-01, -3.74700362e-01],
       [-1.80200463e-01,  9.46488685e-01, -4.32304648e-01,
        -5.86149880e-02, -4.06727142e-01],
       [ 9.98421821e-04, -1.09669459e+00, -6.00825449e-01,
         2.59508058e-01, -1.97333081e+00],
       [-1.51129579e-01,  4.85108239e-01,  6.43899786e-01,
         4.78948243e-01,  6.60031108e-01],
       [ 4.99007363e-01,  1.10639186e+00, -5.40169323e-01,
        -7.86656071e-01, -7.74291223e-01],
       [ 5.88062234e-01,  9.55326466e-01, -2.38313888e-01,
        -9.40627095e-02, -3.14844024e-01],
       [ 1.85524560e+00,  1.44644623e-01,  1.07943503e+00,
         5.83695350e-01, -7.54564663e-01],
       [-1.15621609e-01, -4.58260165e-02, -6.27509214e-01,
        -7.09417795e-01

In [79]:
ust, alt = np.vsplit(m,[2])
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [80]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
np.hsplit(m, [2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [84]:
v = np.array([2,1,4,3,5])

In [85]:
v

array([2, 1, 4, 3, 5])

In [86]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [89]:
mx = np.random.normal(0,1,100).reshape(10,10)
mx = np.sort(mx)
mx

array([[-1.81729182, -0.72051318, -0.47525246, -0.36199123, -0.3485604 ,
         0.0125706 ,  0.07770282,  0.27052737,  0.48368237,  2.3008657 ],
       [-0.93817184, -0.61510124, -0.07704789, -0.05899743, -0.01384145,
         0.00513963,  0.11253989,  0.79761646,  0.96703726,  1.61193992],
       [-1.6694795 , -0.7137379 , -0.65416482, -0.59136648, -0.29092435,
        -0.1151796 ,  0.51122136,  0.5282556 ,  0.61678983,  1.57082126],
       [-1.90825295, -1.35977339, -0.87689933, -0.59760239, -0.59342889,
        -0.19758695, -0.02071973,  0.42527429,  0.55744869,  0.70222446],
       [-0.88012453, -0.48453173, -0.40155082, -0.12845094,  0.24941643,
         0.30263494,  0.37872287,  0.55837602,  0.8187687 ,  1.08317253],
       [-1.39040872, -1.09160125, -0.99449454, -0.48060808, -0.25136759,
        -0.01926522,  0.09898002,  0.56980426,  0.63799048,  1.10708338],
       [-1.27335719, -1.07615383, -1.00999499, -0.76782389, -0.29960175,
        -0.07602873,  0.23270402,  0.24860583

In [93]:
m = np.random.normal(20,5, (3,3))
m

array([[18.43920614, 16.43728769, 21.31692627],
       [25.57503214, 17.09622264, 26.75850043],
       [24.53012925, 25.04877653, 18.69531715]])

In [94]:
np.sort(m, axis = 1)

array([[16.43728769, 18.43920614, 21.31692627],
       [17.09622264, 25.57503214, 26.75850043],
       [18.69531715, 24.53012925, 25.04877653]])

In [95]:
np.sort(m , axis = 0)

array([[18.43920614, 16.43728769, 18.69531715],
       [24.53012925, 17.09622264, 21.31692627],
       [25.57503214, 25.04877653, 26.75850043]])

In [101]:
a = np.random.randint(10, size=(3,5))
a

array([[3, 9, 1, 6, 6],
       [4, 5, 5, 1, 7],
       [8, 0, 3, 3, 1]])

In [102]:
a[0]

array([3, 9, 1, 6, 6])

In [103]:
a[-1]

array([8, 0, 3, 3, 1])

In [104]:
a[0] = 100

In [105]:
a

array([[100, 100, 100, 100, 100],
       [  4,   5,   5,   1,   7],
       [  8,   0,   3,   3,   1]])

In [106]:
a[0,0]

100

In [107]:
a[1,1]

5

In [114]:
a[1,4]

7

In [116]:
a[1, 4] = 99

In [117]:
a[1,4] = 2.2

In [118]:
a

array([[100, 100, 100, 100, 100],
       [  4,   5,   5,   1,   2],
       [  8,   0,   3,   3,   1]])

In [119]:
s = np.arange(20,30)
s

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [120]:
s[0:3]

array([20, 21, 22])

In [121]:
s[:3]

array([20, 21, 22])

In [122]:
s[3:]

array([23, 24, 25, 26, 27, 28, 29])

In [124]:
s[1::2]

array([21, 23, 25, 27, 29])

In [125]:
s[0::2]

array([20, 22, 24, 26, 28])

In [126]:
s[2::2]

array([22, 24, 26, 28])

In [127]:
s[0::3]

array([20, 23, 26, 29])

In [128]:
#iki boyut slice işlemi

In [129]:
m = np.random.randint(10,size = (5,5))
m

array([[0, 3, 3, 8, 0],
       [7, 8, 8, 1, 8],
       [6, 4, 8, 7, 9],
       [3, 5, 0, 7, 8],
       [0, 4, 1, 0, 2]])

In [131]:
m[:,0]

array([0, 7, 6, 3, 0])

In [135]:
m[:,1]

array([3, 8, 4, 5, 4])

In [132]:
m[:,-1]

array([0, 8, 9, 8, 2])

In [134]:
m[:,4]

array([0, 8, 9, 8, 2])

In [136]:
m[0,:]

array([0, 3, 3, 8, 0])

In [137]:
m[1,:]

array([7, 8, 8, 1, 8])

In [138]:
m[2,:]

array([6, 4, 8, 7, 9])

In [140]:
m1 = np.random.randint(25,size = (5,5))
m1

array([[19, 17, 10, 17, 11],
       [24, 21,  8, 22,  1],
       [12, 12,  0, 21, 23],
       [13, 17, 13,  2,  1],
       [15, 18, 19,  1, 22]])

In [141]:
m1[0:2,0:1]

array([[19],
       [24]])

In [143]:
m1[2:3,4:]

array([[23]])

In [144]:
m1[::,:2]

array([[19, 17],
       [24, 21],
       [12, 12],
       [13, 17],
       [15, 18]])

In [145]:
m1[::,2:]

array([[10, 17, 11],
       [ 8, 22,  1],
       [ 0, 21, 23],
       [13,  2,  1],
       [19,  1, 22]])

In [146]:
m1[1:3,0:2]

array([[24, 21],
       [12, 12]])

In [147]:
a1 = np.random.randint(10, size=(5,5))
a1

array([[4, 7, 8, 4, 6],
       [5, 9, 5, 5, 0],
       [6, 5, 0, 3, 4],
       [6, 8, 4, 0, 6],
       [0, 4, 4, 3, 1]])

In [150]:
alt_a1 = a1[0:3, 0:2]
alt_a1

array([[4, 7],
       [5, 9],
       [6, 5]])

In [152]:
alt_a1[0,0] = 9999
alt_a1

array([[9999,    7],
       [   5,    9],
       [   6,    5]])

In [154]:
alt_a1[1,1] = 99
alt_a1

array([[9999,    7],
       [   5,   99],
       [   6,    5]])

In [155]:
a1

array([[9999,    7,    8,    4,    6],
       [   5,   99,    5,    5,    0],
       [   6,    5,    0,    3,    4],
       [   6,    8,    4,    0,    6],
       [   0,    4,    4,    3,    1]])

In [156]:
m2 = np.random.randint(50,size = (5,5))
m2

array([[44,  0, 18, 11, 40],
       [16, 39, 37, 18, 43],
       [26, 35,  2, 47, 25],
       [17, 41, 21, 47, 22],
       [48,  8, 41, 32, 42]])

In [159]:
alt_b = m2[0:3, 0:2].copy()
alt_b

array([[44,  0],
       [16, 39],
       [26, 35]])

In [160]:
alt_b*3

array([[132,   0],
       [ 48, 117],
       [ 78, 105]])

In [161]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [162]:
v[1]

3

In [163]:
v[3]

9

In [164]:
v[5]

15

In [165]:
[v[1], v[3], v[5]]

[3, 9, 15]

In [166]:
al_getir = [1,3,5]

In [167]:
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [168]:
v[al_getir]

array([ 3,  9, 15])

In [169]:
#iki boyutta fancy

In [170]:
m = np.arange(9).reshape((3,3))

In [171]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [172]:
satir = np.array([0,1])
sutun = np.array([1,1])

In [173]:
m[satir, sutun]

array([1, 4])

In [174]:
# basit index ile fancy index

In [175]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [176]:
m[0, [1,2]]

array([1, 2])

In [177]:
#slice 

In [178]:
m[0:,[1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [181]:
m[0:,[0,2]]

array([[0, 2],
       [3, 5],
       [6, 8]])

In [182]:
# koşullu Eleman İşlemler

In [183]:
v = np.array([1,2,3,4,5])

In [184]:
v > 5

array([False, False, False, False, False])

In [185]:
v < 3

array([ True,  True, False, False, False])

In [186]:
v[v < 3]

array([1, 2])

In [187]:
v[v > 3]

array([4, 5])

In [188]:
v[v >= 3]

array([3, 4, 5])

In [189]:
v[v <= 3]

array([1, 2, 3])

In [190]:
v[v == 3]

array([3])

In [191]:
v[v != 3]

array([1, 2, 4, 5])

In [192]:
v

array([1, 2, 3, 4, 5])

In [193]:
v * 2

array([ 2,  4,  6,  8, 10])

In [194]:
v / 5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [195]:
v * 5 / 10

array([0.5, 1. , 1.5, 2. , 2.5])

In [196]:
v**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [197]:
v12 = np.array([1,45,88,66,33])

In [198]:
v12

array([ 1, 45, 88, 66, 33])

In [199]:
v - 1

array([0, 1, 2, 3, 4])

In [200]:
v * 5 /10 - 1 

array([-0.5,  0. ,  0.5,  1. ,  1.5])

In [201]:
# ufunc

In [202]:
np.subtract(v, 1)

array([0, 1, 2, 3, 4])

In [203]:
np.add(v, 1)

array([2, 3, 4, 5, 6])

In [204]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [205]:
np.divide(v, 3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [206]:
np.power(v, 3)

array([  1,   8,  27,  64, 125], dtype=int32)

In [207]:
np.power(v, 10)

array([      1,    1024,   59049, 1048576, 9765625], dtype=int32)

In [208]:
v % 2

array([1, 0, 1, 0, 1], dtype=int32)

In [210]:
v

array([1, 2, 3, 4, 5])

In [209]:
np.mod(v,2)

array([1, 0, 1, 0, 1], dtype=int32)

In [211]:
np.absolute(np.array([-3]))

array([3])

In [213]:
np.absolute(np.random.normal([-1,
                             0],10))

array([ 8.94967451, 15.17493376])

In [214]:
np.sin(360)

0.9589157234143065

In [215]:
np.cos(180)

-0.5984600690578581

In [216]:
v = np.array([1,2,3])

In [217]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [218]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [219]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

In [220]:
?np

## İstatiksel Hesaplamalar

In [225]:
liste = np.random.randint(10,80,70)
liste

array([30, 38, 26, 48, 49, 11, 40, 60, 40, 52, 20, 70, 10, 41, 73, 21, 41,
       58, 11, 75, 71, 37, 78, 68, 57, 39, 54, 34, 27, 39, 53, 13, 70, 17,
       15, 27, 71, 29, 35, 48, 65, 31, 19, 55, 50, 48, 69, 53, 64, 54, 61,
       28, 39, 60, 29, 68, 34, 33, 16, 17, 38, 44, 60, 27, 76, 33, 71, 47,
       25, 15])

In [226]:
np.mean(liste, axis=0)

43.214285714285715

In [227]:
liste.sum()

3025

In [228]:
liste.min()

10

In [230]:
liste.max(axis=0)

78

In [231]:
np.var(liste)

364.6255102040817

In [233]:
np.std(liste)

19.095169813439252

In [235]:
np.corrcoef(liste)

1.0

In [236]:
# iki bilinmeyenli denklem

In [237]:
a = np.array([[5,1] , [1,3]])

In [238]:
b = np.array([12,10])

In [239]:
a

array([[5, 1],
       [1, 3]])

In [240]:
b

array([12, 10])

In [241]:
x = np.linalg.solve(a, b)
x

array([1.85714286, 2.71428571])

In [242]:

np.arange(0,10, 2)


array([0, 2, 4, 6, 8])

In [243]:
a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])
a[:2, :3]

array([[4, 7, 4],
       [2, 5, 0]])

In [245]:
v=np.array([ 0, 3, 6, 9, 12, 15, 18, 21, 24, 27])


[v[9], v[0]]

[27, 0]

In [246]:

a=np.array([[4, 7, 4, 5, 9],
            [2, 5, 0, 7, 7],
            [1, 9, 0, 8, 2]])



a[:,2]

array([4, 0, 0])

In [248]:
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [249]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [251]:
np.array([3.14, 4,6,1.2])

array([3.14, 4.  , 6.  , 1.2 ])

In [252]:
5*np.array([1,2,3])

array([ 5, 10, 15])