## Veri Bilimi İstatistik

Örnek Teorisi

In [2]:
import numpy as np
populasyon = np.random.randint(0,80,10000)

In [3]:
populasyon[0:10]

array([68, 69, 10, 64, 42, 10, 46, 44, 63,  4])

In [7]:
#orneklem cekimi
np.random.seed(10)
orneklem = np.random.choice(a = populasyon, size =100)
orneklem[0:10]

array([69, 57, 16, 77, 65, 43, 40, 73, 48,  7])

In [8]:
orneklem.mean()

39.74

In [9]:
populasyon.mean()

39.2317

In [10]:
#orneklem dağılımı
np.random.seed(18)
orneklem1 = np.random.choice(a = populasyon, size =100)
orneklem2 = np.random.choice(a = populasyon, size =100)
orneklem3 = np.random.choice(a = populasyon, size =100)
orneklem4 = np.random.choice(a = populasyon, size =100)
orneklem5 = np.random.choice(a = populasyon, size =100)
orneklem6 = np.random.choice(a = populasyon, size =100)
orneklem7 = np.random.choice(a = populasyon, size =100)
orneklem8 = np.random.choice(a = populasyon, size =100)
orneklem9 = np.random.choice(a = populasyon, size =100)
orneklem10 = np.random.choice(a = populasyon, size =100)

In [12]:
print((orneklem1.mean()+orneklem2.mean()+orneklem3.mean()+orneklem4.mean()+
      orneklem5.mean()+orneklem6.mean()+orneklem7.mean()+orneklem8.mean()+
      orneklem9.mean()+orneklem10.mean())/10)

38.221000000000004


# Betimsel İstatistik

In [13]:
import seaborn as sns
tips = sns.load_dataset("tips")
df = tips.copy()
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [14]:
df.describe().T

count       mean       std   min      25%     50%      75%    max
total_bill  244.0  19.785943  8.902412  3.07  13.3475  17.795  24.1275  50.81
tip         244.0   2.998279  1.383638  1.00   2.0000   2.900   3.5625  10.00
size        244.0   2.569672  0.951100  1.00   2.0000   2.000   3.0000   6.00

In [17]:
import researchpy as rp

In [19]:
rp.summary_cont(df[["total_bill","tip","size"]])

Variable      N     Mean      SD      SE  95% Conf.  Interval
0  total_bill  244.0  19.7859  8.9024  0.5699    18.6633   20.9086
1         tip  244.0   2.9983  1.3836  0.0886     2.8238    3.1728
2        size  244.0   2.5697  0.9511  0.0609     2.4497    2.6896

In [21]:
rp.summary_cat(df[["sex","smoker","day"]])

Variable Outcome  Count  Percent
0      sex    Male    157    64.34
1           Female     87    35.66
2   smoker      No    151    61.89
3              Yes     93    38.11
4      day     Sat     87    35.66
5              Sun     76    31.15
6             Thur     62    25.41
7              Fri     19     7.79

In [22]:
df[["tip","total_bill"]].cov()

tip  total_bill
tip         1.914455    8.323502
total_bill  8.323502   79.252939

In [23]:
df[["tip","total_bill"]].corr()

tip  total_bill
tip         1.000000    0.675734
total_bill  0.675734    1.000000

## İş Ugulaması

In [24]:
import numpy as np
fiyatlar = np.random.randint(10,110,1000)

In [25]:
fiyatlar.mean()

58.696

In [26]:
import statsmodels.stats.api as sms

In [27]:
sms.DescrStatsW(fiyatlar).tconfint_mean()

(56.91978189769334, 60.472218102306655)

# Olasılık Dağılımları

### Bernoulli Dağılımı

In [28]:
from scipy.stats import bernoulli

In [29]:
p = 0.6

In [30]:
rv = bernoulli(p)
rv.pmf(k=1)

0.6

In [31]:
rv.pmf(k=0)

0.4

### Büyük Sayılar Yasası

In [47]:
rng = np.random.RandomState(123)
for i in np.arange(1,25):
    deney_sayisi = 2**i
    yazi_turalar = rng.randint(0,2, size=deney_sayisi)
    yazi_olasılıkları = np.mean(yazi_turalar)
    print("Atış Sayısı: ", deney_sayisi,"---","Yazı Olasılığı: %.2f"% (yazi_olasılıkları*100),"%")

Atış Sayısı:  2 --- Yazı Olasılığı: 50.00 %
Atış Sayısı:  4 --- Yazı Olasılığı: 0.00 %
Atış Sayısı:  8 --- Yazı Olasılığı: 62.50 %
Atış Sayısı:  16 --- Yazı Olasılığı: 43.75 %
Atış Sayısı:  32 --- Yazı Olasılığı: 46.88 %
Atış Sayısı:  64 --- Yazı Olasılığı: 56.25 %
Atış Sayısı:  128 --- Yazı Olasılığı: 50.78 %
Atış Sayısı:  256 --- Yazı Olasılığı: 52.73 %
Atış Sayısı:  512 --- Yazı Olasılığı: 52.93 %
Atış Sayısı:  1024 --- Yazı Olasılığı: 50.20 %
Atış Sayısı:  2048 --- Yazı Olasılığı: 48.58 %
Atış Sayısı:  4096 --- Yazı Olasılığı: 49.49 %
Atış Sayısı:  8192 --- Yazı Olasılığı: 49.58 %
Atış Sayısı:  16384 --- Yazı Olasılığı: 49.96 %
Atış Sayısı:  32768 --- Yazı Olasılığı: 50.00 %
Atış Sayısı:  65536 --- Yazı Olasılığı: 49.68 %
Atış Sayısı:  131072 --- Yazı Olasılığı: 49.97 %
Atış Sayısı:  262144 --- Yazı Olasılığı: 50.13 %
Atış Sayısı:  524288 --- Yazı Olasılığı: 50.01 %
Atış Sayısı:  1048576 --- Yazı Olasılığı: 50.09 %
Atış Sayısı:  2097152 --- Yazı Olasılığı: 50.01 %
Atış Sayısı:  419

In [48]:
rng.randint(0,2, size=5)

array([1, 1, 0, 0, 1])

### Normal Dağılım Problemi

In [50]:
from scipy.stats import norm

In [52]:
# 90 dan fazla olma olasılığı
1-norm.cdf(90,80,5)

0.02275013194817921

In [53]:
#70 den fazla olma olasılığı
1-norm.cdf(70,80,5)

0.9772498680518208

In [54]:
#73 den az olma olasılığı
norm.cdf(73,80,5)

0.08075665923377107

In [55]:
#85 90 arası olma olasılığı
norm.cdf(90,80,5) - norm.cdf(85,80,5)

0.13590512198327787

In [56]:
np.random.randint(140, 220, 1000)

array([164, 155, 198, 202, 211, 204, 145, 201, 208, 177, 202, 153, 216,
       172, 143, 143, 147, 204, 194, 188, 190, 196, 204, 191, 210, 148,
       205, 192, 211, 153, 170, 188, 154, 150, 186, 200, 165, 179, 205,
       198, 182, 187, 213, 141, 179, 182, 148, 204, 166, 149, 173, 178,
       197, 174, 196, 168, 208, 167, 184, 177, 153, 148, 153, 195, 193,
       179, 185, 168, 181, 163, 210, 149, 216, 205, 193, 219, 179, 201,
       214, 189, 143, 209, 153, 147, 177, 190, 164, 156, 204, 202, 163,
       188, 157, 175, 178, 143, 142, 155, 212, 159, 149, 146, 188, 192,
       181, 169, 167, 175, 210, 187, 154, 147, 194, 202, 158, 145, 200,
       178, 161, 200, 144, 162, 208, 159, 150, 198, 141, 149, 217, 141,
       177, 155, 194, 167, 205, 203, 169, 188, 217, 203, 217, 176, 152,
       144, 140, 174, 174, 142, 203, 157, 162, 151, 215, 161, 189, 177,
       183, 206, 154, 217, 196, 189, 152, 164, 155, 176, 172, 188, 188,
       174, 216, 183, 169, 164, 194, 215, 203, 154, 152, 143, 20